// =============================================
// DATA.JS — Portfolio Content Repository
// =============================================

window.PORTFOLIO = {

  // ------ TAGLINES (rotating) ------
  taglines: [
    "Biomedical Engineer",
    "AI / ML Researcher",
    "Web Developer and Graphic Designer",
  ],

  // ------ EXPERIENCE ------
  experience: [
    {
      company: "Tectum Techno Space Pvt. Ltd.",
      role: "AI Research Intern – Pharmacogenomics",
      spec: "Pharmacogenomics",
      date: "Oct 2025 – Present",
      prestige: "Industry Research",
      accentColor: "oklch(0.72 0.16 200)",
      accentBg: "oklch(0.72 0.16 200 / 0.12)",
      icon: "microscope",
      bullets: [
        "Designed and maintained end-to-end data pipelines in Python for curating, cleaning, and preparing pharmaceutical, genomic, and drug-gene datasets.",
        "Trained and evaluated ML models (NLP and structured-data) for drug response prediction and adverse event mapping using TensorFlow and PyTorch.",
        "Built interactive dashboards and Jupyter Notebooks to communicate complex model outputs to pharmacologists and regulatory stakeholders.",
      ],
      tech: ["Python", "TensorFlow", "PyTorch", "NLP", "Scikit-learn"],
    },
    {
      company: "IIT Madras HTIC MedTech Incubator",
      role: "Academic Intern – Medical Device R&D",
      spec: "MedTech R&D",
      date: "Jan 2025 – April 2025",
      prestige: "IIT Madras",
      accentColor: "oklch(0.65 0.20 290)",
      accentBg: "oklch(0.65 0.20 290 / 0.12)",
      icon: "university",
      bullets: [
        "Contributing to medical device research, design, and testing in a MedTech incubator, focusing on MDR compliance and user experience.",
        "Conducting clinical user requirements analysis and translating findings into functional device specifications using patient-centred design thinking.",
        "Reviewed CDSCO and FDA regulatory frameworks to build competence in medical device safety standards.",
      ],
      tech: ["MDR", "CDSCO", "FDA", "Design Thinking"],
    },
    {
      company: "Dedrock – The Universe",
      role: "Graphic Designer",
      spec: "Creative Design",
      date: "Aug 2024 – Dec 2024",
      prestige: "Creative",
      accentColor: "oklch(0.65 0.18 10)",
      accentBg: "oklch(0.65 0.18 10 / 0.12)",
      icon: "palette",
      bullets: [
        "Delivered on-brand digital and print assets—banners, product listings, mockups—using Adobe Illustrator, Photoshop, and Canva.",
        "Managed multiple design projects independently under tight deadlines, demonstrating strong time management and creative execution.",
        "Ensured visual consistency across all campaign deliverables for a global universe-themed brand identity.",
      ],
      tech: ["Illustrator", "Photoshop", "Canva", "Graphic Design"],
    },
    {
      company: "EvePaper",
      role: "Research & Promotion Intern",
      spec: "Data Research",
      date: "Aug 2024 – Dec 2024",
      prestige: "Academic Research",
      accentColor: "oklch(0.72 0.16 65)",
      accentBg: "oklch(0.72 0.16 65 / 0.12)",
      icon: "search",
      bullets: [
        "Conducted structured secondary research and data collection using Python web scraping and manual database navigation.",
        "Compiled findings into actionable written reports for academic and promotional workflows.",
        "Managed concurrent research workstreams independently, meeting deliverable timelines with accurate, well-documented outputs.",
      ],
      tech: ["Python", "Web Scraping", "Market Research", "Data Collection"],
    },
  ],

  // ------ PROJECTS ------
  projects: [
    {
      id: "audiometer",
      categories: ["Biomedical Engineering", "Signal Processing"],
      title: "Raspberry Pi Portable Audiometer",
      description: "Designed, built, and validated a portable clinical-grade audiometer for accessible hearing diagnostics across paediatric and multilingual populations.",
      features: ["PTA & Speech Audiometry", "Real-time Signal Generation", "Paediatric Testing", "Portable Hardware"],
      visual: "audiometer",
      link: "https://github.com/prasanna0810/Raspberry-Pi-based-portable-audiometer",
      linkLabel: "View on GitHub",
    },
    {
      id: "component-detect",
      categories: ["AI", "Computer Vision"],
      title: "Electronic Component Detection",
      description: "Deep learning image classification system (TensorFlow/PyTorch) to automate component identification with a production-ready Flask REST API.",
      features: ["Deep Learning (CNN)", "Flask REST API", "Web interface", "Production-ready"],
      visual: "ai",
      link: "https://github.com/prasanna0810/AI-Electronic-Components-Identification",
      linkLabel: "View on GitHub",
    },
    {
      id: "drug",
      categories: ["Data Science", "Web App"],
      title: "Drug Classification Engine",
      description: "AI-driven engine classifying 200 k+ drugs into 150 therapeutic tiers with a CIMS-style Flask search portal.",
      features: ["150-Tier Taxonomy", "SQLite + Flask", "Gemini Semantics"],
      visual: "small",
      link: null,
      linkLabel: "Explore",
    },
    {
      id: "sme",
      categories: ["Enterprise", "Dashboard"],
      title: "SME Reporting System",
      description: "Executive SaaS dashboard with dynamic bar-graph visualisations, risk heat-maps, and Excel export for SME financial reporting.",
      features: ["Risk Heat-Map", "Excel Export", "Animated Charts"],
      visual: "small",
      link: null,
      linkLabel: "Explore",
    },
  ],

  // ------ CERTIFICATIONS ------
  certifications: [
    {
      title: "Introduction to Generative AI Learning Path",
      issuer: "Google Cloud",
      category: "AI & ML",
      icon: "sparkles",
      badgeBg: "oklch(0.12 0.04 200 / 0.5)",
      badgeBorder: "oklch(0.5 0.10 200 / 0.25)",
      file: "https://www.credly.com/badges/2064ccc6-a578-479d-bf28-da43bc7ce685",
      isExternal: true,
    },
    {
      title: "Introduction to Data Science",
      issuer: "Infosys Springboard",
      category: "Data Science",
      icon: "bar-chart-2",
      badgeBg: "oklch(0.12 0.04 270 / 0.5)",
      badgeBorder: "oklch(0.5 0.10 270 / 0.25)",
      file: "Introduction to Data Science_Infosys.pdf",
    },
    {
      title: "What Is Generative AI",
      issuer: "LinkedIn Learning",
      category: "AI & ML",
      icon: "brain",
      badgeBg: "oklch(0.12 0.04 200 / 0.5)",
      badgeBorder: "oklch(0.5 0.10 200 / 0.25)",
      file: "What Is Generative AI_LinkedIn Learning.pdf",
    },
    {
      title: "Programming, Data Structures & Algorithms Using Python",
      issuer: "NPTEL",
      category: "Data Science",
      icon: "code-2",
      badgeBg: "oklch(0.12 0.04 270 / 0.5)",
      badgeBorder: "oklch(0.5 0.10 270 / 0.25)",
      file: "Programming, Data Structures & Algorithms Using Python_NPTEL.pdf",
    },
    {
      title: "Data Science for Engineers",
      issuer: "NPTEL",
      category: "Data Science",
      icon: "database",
      badgeBg: "oklch(0.12 0.04 270 / 0.5)",
      badgeBorder: "oklch(0.5 0.10 270 / 0.25)",
      file: "Data Science for Engineers_NPTEL.pdf",
    },
    {
      title: "Computer Vision 101",
      issuer: "Infosys Springboard",
      category: "AI & ML",
      icon: "eye",
      badgeBg: "oklch(0.12 0.04 200 / 0.5)",
      badgeBorder: "oklch(0.5 0.10 200 / 0.25)",
      file: "Computer Vision 101_Infosys.pdf",
    },
    {
      title: "Introduction to Natural Language Processing",
      issuer: "Infosys Springboard",
      category: "AI & ML",
      icon: "message-square",
      badgeBg: "oklch(0.12 0.04 200 / 0.5)",
      badgeBorder: "oklch(0.5 0.10 200 / 0.25)",
      file: "Introduction to Natural Language Processing_Infosys.pdf",
    },
    {
      title: "Introduction to Deep Learning",
      issuer: "Infosys Springboard",
      category: "AI & ML",
      icon: "layers",
      badgeBg: "oklch(0.12 0.04 200 / 0.5)",
      badgeBorder: "oklch(0.5 0.10 200 / 0.25)",
      file: "Introduction to Deep Learning_Infosys.pdf",
    },
    {
      title: "Introduction to Artificial Intelligence",
      issuer: "Infosys Springboard",
      category: "AI & ML",
      icon: "bot",
      badgeBg: "oklch(0.12 0.04 200 / 0.5)",
      badgeBorder: "oklch(0.5 0.10 200 / 0.25)",
      file: "Introduction to Artificial Intelligence_Infosys .pdf",
    },
    {
      title: "Siemens Mobility– Operations Industrial Engineer Simulation",
      issuer: "Forage",
      category: "Engineering",
      icon: "settings",
      badgeBg: "oklch(0.12 0.04 65 / 0.5)",
      badgeBorder: "oklch(0.5 0.10 65 / 0.25)",
      file: "Siemens Mobility– Operations Industrial Engineer Job Simulation_Forage.pdf",
    },
    {
      title: "Robotic Process Automation (RPA)",
      issuer: "Infosys Springboard",
      category: "Engineering",
      icon: "cpu",
      badgeBg: "oklch(0.12 0.04 65 / 0.5)",
      badgeBorder: "oklch(0.5 0.10 65 / 0.25)",
      file: "Introduction to Robotic Process Automation (RPA)_Infosys.pdf",
    },
    {
      title: "Introduction to Programming in C",
      issuer: "NPTEL",
      category: "Engineering",
      icon: "terminal",
      badgeBg: "oklch(0.12 0.04 65 / 0.5)",
      badgeBorder: "oklch(0.5 0.10 65 / 0.25)",
      file: "Introduction to Programming in C_NPTEL.pdf",
    },
    {
      title: "Nestlé Sustainability E-Learning 2024",
      issuer: "Nestlé",
      category: "Professional",
      icon: "leaf",
      badgeBg: "oklch(0.12 0.04 150 / 0.5)",
      badgeBorder: "oklch(0.5 0.10 150 / 0.25)",
      file: "Nestlé E-Learning 2024– Sustainability_Nestlé.pdf",
    },
    {
      title: "Email Writing Skills",
      issuer: "Infosys Springboard",
      category: "Soft Skills",
      icon: "mail",
      badgeBg: "oklch(0.12 0.04 320 / 0.5)",
      badgeBorder: "oklch(0.5 0.10 320 / 0.25)",
      file: "Email Writing Skills_Infosys .pdf",
    },
    {
      title: "Time Management",
      issuer: "Infosys Springboard",
      category: "Soft Skills",
      icon: "clock",
      badgeBg: "oklch(0.12 0.04 320 / 0.5)",
      badgeBorder: "oklch(0.5 0.10 320 / 0.25)",
      file: "Time Management_Infosys.pdf",
    },
    {
      title: "ChatGPT for Microsoft PowerPoint Presentations",
      issuer: "Great Learning",
      category: "AI Tech",
      icon: "monitor",
      badgeBg: "oklch(0.12 0.04 200 / 0.5)",
      badgeBorder: "oklch(0.5 0.10 200 / 0.25)",
      file: "ChatGPT for Microsoft PowerPoint Presentations_Great Learning.pdf",
    },
  ],

  // ------ SKILLS ------
  skills: {
    panels: [
      {
        name: "AI & Machine Learning",
        icon: "brain",
        hue: 200,
        wide: false,
        items: ["TensorFlow", "PyTorch", "Scikit-learn", "Keras", "OpenCV", "Gemini API"],
      },
      {
        name: "Signal & Biomedical Processing",
        icon: "activity",
        hue: 10,
        wide: false,
        isBiomedical: true,
        items: [
          { group: "Signals", tags: ["EEG", "ECG", "EMG", "MFCC", "FFT"] },
          { group: "Tools", tags: ["MATLAB", "LabVIEW", "BioSPPy"] },
        ],
      },
      {
        name: "Languages & Frameworks",
        icon: "code",
        hue: 270,
        wide: true,
        items: [
          { group: "Languages", tags: ["Python", "JavaScript", "C", "Java", "SQL"] },
          { group: "Frameworks", tags: ["Flask", "Streamlit", "React", "Node.js"] },
          { group: "ML Libraries", tags: ["pandas", "NumPy", "Matplotlib", "SciPy"] },
        ],
      },
      {
        name: "Web & Cloud",
        icon: "globe",
        hue: 195,
        wide: false,
        items: ["HTML5", "CSS3", "REST APIs", "Google Apps Script", "GitHub Pages", "SQLite"],
      },
      {
        name: "Research & Tools",
        icon: "test-tube-2",
        hue: 150,
        wide: false,
        items: ["LaTeX", "Jupyter", "Git", "Figma", "Microsoft Excel", "Canva"],
      },
    ],

    // Galaxy orbital data: each orbit is an array of skill names
    galaxy: [
      // orbit 0 (innermost)
      ["Python", "TensorFlow", "MATLAB"],
      // orbit 1
      ["Signal Proc.", "EEG/ECG", "OpenCV", "Flask", "HTML/CSS"],
      // orbit 2
      ["Scikit-learn", "pandas", "React", "Gemini API", "Git", "Streamlit"],
      // orbit 3 (outermost)
      ["LaTeX", "SQLite", "Node.js", "LabVIEW", "NumPy", "Keras", "MFCC", "REST API"],
    ],
  },
};
